apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-backend-deployment
  labels:
    deployment: canary-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-backend
  template:
    metadata:
      labels:
        app: canary-backend
    spec:
      containers:
        - name: canary-backend
          image: ekke020/canary-backend:86a6e19
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
