apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    deployment: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: backend
    spec:
      containers:
        - name: canary-backend
          image: ekke020/canary-backend:d4b5a68
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
