apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canary-backend-release
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-backend-deployment
  service:
    port: 8080
    targetPort: 7878
  analysis:
    interval: 30s
    threshold: 10
    maxWeight: 100
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m