apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: backend
  name: canary-backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: canary-backend
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: canary-backend
    spec:
      containers:
      - image: ekke020/canary-backend:0960708
        name: canary-backend
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
