apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: backend
  name: backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: backend
    spec:
      containers:
      - image: ekke020/canary-backend:92fe703
        name: canary-backend
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canary-backend
  namespace: backend
spec:
  analysis:
    interval: 10s
    maxWeight: 100
    metrics:
    - interval: 1m
      name: request-success-rate
      thresholdRange:
        min: 99
    - interval: 30s
      name: request-duration
      thresholdRange:
        max: 500
    stepWeight: 10
    threshold: 5
  service:
    port: 8080
    targetPort: 7878
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
