apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: backend
  namespace: flux-system
spec:
  dependsOn:
  - name: flagger
  interval: 1m0s
  path: ./raw-configs/canary-backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: backend-primary
      namespace: backend
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  dependsOn:
  - name: backend
  interval: 1m0s
  path: ./raw-configs/canary-frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: frontend