apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smi
  namespace: linkerd
spec:
  timeout: 3m
  interval: 10m
  releaseName: linkerd-smi
  targetNamespace: linkerd-smi
  storageNamespace: linkerd-smi
  chart:
    spec:
      chart: linkerd-smi
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 40m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace