apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/linkerd/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: crds
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-control-plane
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-crds
  interval: 1m0s
  path: ./platform/linkerd/control-plane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-destination
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-control-plane
  interval: 1m0s
  path: ./platform/linkerd/viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metrics-api
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: tap
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: tap-injector
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: linkerd-viz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-smi
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  interval: 1m0s
  path: ./platform/linkerd/smi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: smi
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-smi
  interval: 1m0s
  path: ./platform/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: linkerd