apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: canary-backend
  name: canary-server
  namespace: backend
spec:
  selector:
    matchLabels:
      app: canary-server
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: canary-server
    spec:
      containers:
      - image: ekke020/canary-backend:0960708
        name: canary-server
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: canary-hpa
  namespace: backend
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 99
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-server
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canary-backend
  namespace: backend
spec:
  analysis:
    interval: 30s
    maxWeight: 100
    metrics:
    - interval: 1m
      name: request-success-rate
      thresholdRange:
        min: 99
    - interval: 30s
      name: request-duration
      thresholdRange:
        max: 500
    stepWeight: 5
    threshold: 5
  progressDeadlineSeconds: 60
  service:
    port: 8080
    targetPort: 7878
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-server
