apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-server
    service: canary-srv
  name: backend-srv
  namespace: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7878
  selector:
    app: canary-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: canary-backend
  name: canary-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-server
  template:
    metadata:
      labels:
        app: canary-server
    spec:
      containers:
      - image: ekke020/canary-backend:bffce8a
        name: canary-server
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canary-backend
  namespace: backend
spec:
  analysis:
    interval: 30s
    maxWeight: 100
    stepWeight: 5
    threshold: 5
  progressDeadlineSeconds: 60
  service:
    port: 8080
    targetPort: 7878
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-server
