apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-frontend
    service: frontend-srv
  name: frontend-srv
  namespace: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: canary-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: frontend
  name: canary-frontend
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: canary-frontend
    replicas: 1
  template:
    metadata:
      labels:
        app: canary-frontend
    spec:
      containers:
      - image: ekke020/canary-frontend:a621bc1
        name: canary-frontend
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
spec:
  defaultBackend:
    service:
      name: frontend-srv
      port:
        number: 80
