apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-backend-service
    service: canary-backend-service
  name: canary-backend-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7878
  selector:
    app: canary-backend
  type: NodePort
---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    deployment: canary-backend
  name: canary-backend-deployment
spec:
  selector:
    matchLabels:
      app: canary-backend
    replicas: 2
  template:
    metadata:
      labels:
        app: canary-backend
    spec:
      containers:
      - image: ekke020/canary-backend:f26d9fe
        name: canary-backend
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-backend-ingress
spec:
  defaultBackend:
    service:
      name: canary-backend-service
      port:
        number: 8080
