apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: viz
  namespace: linkerd-viz
spec:
  timeout: 3m
  interval: 10m
  chart:
    spec:
      chart: linkerd-viz
      version: 30.3.x
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 40m
  values:
    installNamespace: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace