apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
bases:
  - github.com/fluxcd/flagger/kustomize/base/flagger
patches:
  - path: flagger.yaml 
    target:
      kind: Deployment
      name: flagger
  - path: role-binding.yaml
    target:
      kind: ClusterRoleBinding
      name: flagger